/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Designer;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Jadhav
 */
public class Editor extends javax.swing.JFrame {
private boolean waitingForLocationClick = false;
private boolean lookingToRemove = false;
private boolean button = false;
private boolean panel = false;
private boolean label = false;
private boolean checkbox = false;
private boolean radiobutton = false;
private boolean combobox = false;
private boolean list = false;
private boolean textarea = false;
private boolean textfield = false;
private boolean running = true;


int width = 0;
int height = 0;
int columns=0;
int tcolumns;
int rows=0;

    private JButton buttonToPlace;    
    private JPanel panelToPlace;    
    private JLabel labelToPlace;    
    private JCheckBox checkboxToPlace;    
    private JRadioButton radiobuttonToPlace;    
    private JComboBox comboboxToPlace;    
    private JList listToPlace;    
    private JTextArea textareaToPlace;     
    private JTextArea textareaToPlace2;    
    private JTextField textfieldToPlace;

Color bkclr;
boolean bckColor = false;

Color foreclr;
boolean foreColor = false;


    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        
        jPanel3.addMouseListener(pointSelectorListener);
        
        remove.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lookingToRemove = true;
                jPanel3.setCursor(new Cursor(Cursor.MOVE_CURSOR));
            }
        });
        
    }
    
//    public void CustomCursor(){
////        Toolkit tk = Toolkit.getDefaultToolkit();
////                    Image image = tk.getImage("remove.png");
////                    Point p = new Point(this.getX(),this.getY());
////                  Cursor customCursor = tk.createCustomCursor(image,p,"remove.png");
//                  jPanel3.setCursor(new Cursor(Cursor.MOVE_CURSOR));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ForeColor = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        BckColor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addPanel = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addLabel = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addCheckbox = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addRadiobutton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addCombobox = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        addList = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        addTextarea = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        addTextfield = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UI Editor");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(230, 250, 254));

        ForeColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/foreColor.png"))); // NOI18N
        ForeColor.setToolTipText("Choose a Forecolor for Component");
        ForeColor.setBorder(null);
        ForeColor.setBorderPainted(false);
        ForeColor.setContentAreaFilled(false);
        ForeColor.setFocusPainted(false);
        ForeColor.setFocusable(false);
        ForeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForeColorActionPerformed(evt);
            }
        });

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        remove.setToolTipText("Remove a Component");
        remove.setBorder(null);
        remove.setBorderPainted(false);
        remove.setContentAreaFilled(false);
        remove.setFocusPainted(false);
        remove.setFocusable(false);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.png"))); // NOI18N
        jButton4.setToolTipText("Home");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paint.png"))); // NOI18N
        jButton5.setToolTipText("Paint");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Info.png"))); // NOI18N
        jButton6.setToolTipText("About this editor");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        BckColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgColor.png"))); // NOI18N
        BckColor.setToolTipText("Choose a Background color for Component");
        BckColor.setBorder(null);
        BckColor.setBorderPainted(false);
        BckColor.setContentAreaFilled(false);
        BckColor.setFocusPainted(false);
        BckColor.setFocusable(false);
        BckColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BckColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(ForeColor)
                    .addComponent(remove)
                    .addComponent(BckColor)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BckColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ForeColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 70, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 900, 600));

        jPanel4.setBackground(new java.awt.Color(143, 45, 86));

        jLabel8.setBackground(new java.awt.Color(185, 251, 192));
        jLabel8.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("COMPONENT Tray");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 70));

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(246, 255, 248));

        jPanel15.setBackground(new java.awt.Color(251, 248, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PANEL");

        addPanel.setBackground(new java.awt.Color(255, 255, 255));
        addPanel.setForeground(new java.awt.Color(255, 255, 255));
        addPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addPanel.setToolTipText("Add the Panel");
        addPanel.setBorder(null);
        addPanel.setBorderPainted(false);
        addPanel.setContentAreaFilled(false);
        addPanel.setFocusPainted(false);
        addPanel.setFocusable(false);
        addPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPanel)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(253, 228, 207));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("LABEL");

        addLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addLabel.setToolTipText("Add the Label");
        addLabel.setBorder(null);
        addLabel.setBorderPainted(false);
        addLabel.setContentAreaFilled(false);
        addLabel.setFocusPainted(false);
        addLabel.setFocusable(false);
        addLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addLabel)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(addLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 205, 242));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("BUTTON");

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addButton.setToolTipText("Add the Button");
        addButton.setBorder(null);
        addButton.setBorderPainted(false);
        addButton.setContentAreaFilled(false);
        addButton.setFocusPainted(false);
        addButton.setFocusable(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel17.setBackground(new java.awt.Color(241, 192, 200));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CHECKBOX");

        addCheckbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addCheckbox.setToolTipText("Add the checkbox");
        addCheckbox.setBorder(null);
        addCheckbox.setBorderPainted(false);
        addCheckbox.setContentAreaFilled(false);
        addCheckbox.setFocusPainted(false);
        addCheckbox.setFocusable(false);
        addCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCheckbox)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBackground(new java.awt.Color(207, 186, 240));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("RADIOBUTTON");

        addRadiobutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addRadiobutton.setToolTipText("Add the radiobutton");
        addRadiobutton.setBorder(null);
        addRadiobutton.setBorderPainted(false);
        addRadiobutton.setContentAreaFilled(false);
        addRadiobutton.setFocusPainted(false);
        addRadiobutton.setFocusable(false);
        addRadiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRadiobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(addRadiobutton)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addRadiobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel13.setBackground(new java.awt.Color(163, 196, 243));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("COMBOBOX");

        addCombobox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addCombobox.setToolTipText("Add the combobox");
        addCombobox.setBorder(null);
        addCombobox.setBorderPainted(false);
        addCombobox.setContentAreaFilled(false);
        addCombobox.setFocusPainted(false);
        addCombobox.setFocusable(false);
        addCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCombobox)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(addCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(144, 219, 244));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("LIST");

        addList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addList.setToolTipText("Add the List");
        addList.setBorder(null);
        addList.setBorderPainted(false);
        addList.setContentAreaFilled(false);
        addList.setFocusPainted(false);
        addList.setFocusable(false);
        addList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addList)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addList, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel24.setBackground(new java.awt.Color(142, 236, 245));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("TEXTAREA");

        addTextarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addTextarea.setToolTipText("Add the TextArea");
        addTextarea.setBorder(null);
        addTextarea.setBorderPainted(false);
        addTextarea.setContentAreaFilled(false);
        addTextarea.setFocusPainted(false);
        addTextarea.setFocusable(false);
        addTextarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTextarea)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(addTextarea, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel25.setBackground(new java.awt.Color(152, 245, 225));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("TEXFIELD");

        addTextfield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addTextfield.setToolTipText("Add the Textfield");
        addTextfield.setBorder(null);
        addTextfield.setBorderPainted(false);
        addTextfield.setContentAreaFilled(false);
        addTextfield.setFocusPainted(false);
        addTextfield.setFocusable(false);
        addTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTextfield)
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 530));

        setSize(new java.awt.Dimension(1242, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Paint p = new Paint();
        p.show();
        
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        WelcomePage wp = new WelcomePage();
        wp.show();
        
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addButton(JOptionPane.showInputDialog("Name of the new button:"));
                            jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_addButtonActionPerformed

    private void addPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPanelActionPerformed
        // TODO add your handling code here:
        addPanel(JOptionPane.showInputDialog("Width of the new panel:"),JOptionPane.showInputDialog("Height of the new panel:"));
        jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
    }//GEN-LAST:event_addPanelActionPerformed

    private void addLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLabelActionPerformed
        // TODO add your handling code here:
        addLabel(JOptionPane.showInputDialog("Enter the text:"));
                    jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_addLabelActionPerformed

    private void addCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCheckboxActionPerformed
        // TODO add your handling code here:
        addCheckbox(JOptionPane.showInputDialog("Enter the text:"));
                            jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_addCheckboxActionPerformed

    private void addRadiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRadiobuttonActionPerformed
        // TODO add your handling code here:
        addRadiobutton(JOptionPane.showInputDialog("Enter the text:"));
                            jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_addRadiobuttonActionPerformed

    private void addComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComboboxActionPerformed
        // TODO add your handling code here:addCombobox
        String item = JOptionPane.showInputDialog("Enter the number of items:");
        int items = Integer.parseInt(item);
        String[] itemName = new String[20];
        for (int i=0; i<items; i++){
            itemName[i] = JOptionPane.showInputDialog("Enter item number "+ (i+1) +": ");
        }
        addCombobox(itemName);
                            jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_addComboboxActionPerformed

    private void addListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListActionPerformed
        // TODO add your handling code here:
        String item = JOptionPane.showInputDialog("Enter the number of items:");
        int items = Integer.parseInt(item);
        String[] itemName = new String[20];
        for (int i=0; i<items; i++){
            itemName[i] = JOptionPane.showInputDialog("Enter item number "+ (i+1) +": ");
        }
        addList(itemName);
                            jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_addListActionPerformed

    private void addTextareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextareaActionPerformed
        // TODO add your handling code here:
        addTextarea(JOptionPane.showInputDialog("Enter No. of Columns:"),JOptionPane.showInputDialog("Enter No. of Rows:"),JOptionPane.showInputDialog("Text to display in Textarea:"));
                            jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_addTextareaActionPerformed

    private void addTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextfieldActionPerformed
        // TODO add your handling code here:
        addTextfield(JOptionPane.showInputDialog("Enter No. of Columns:"),JOptionPane.showInputDialog("Text to display in Textarea:"));
                            jPanel3.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));

    }//GEN-LAST:event_addTextfieldActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void BckColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BckColorActionPerformed
        bkclr = JColorChooser.showDialog(this, "Select a Color to set as Background", bkclr);
        bckColor=true;
    }//GEN-LAST:event_BckColorActionPerformed

    private void ForeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForeColorActionPerformed
        foreclr = JColorChooser.showDialog(this, "Select a Color to set as ForeColor", foreclr);
        foreColor=true;
    }//GEN-LAST:event_ForeColorActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JOptionPane.showMessageDialog(this, "Welcome to UI Editor/ Designer \n"
               + "To Select any Component click the PLUS button and then cursor changes to CROSSHAIR cursor and then place the component\n"
               + "To Remove any Component click the TRASH icon and then cursor changes to MOVE cursor and select the component to be removed \n"
               + "To Change the ForeColor or BackroundColor of the Components click on Right top 1st Icon and Right top 2nd Icon respectively\n");
    }//GEN-LAST:event_jButton6ActionPerformed

    public void addButton(String name) {
        button =true;
        JButton b = new JButton(name);
        b.setActionCommand(name);
        b.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (lookingToRemove) {
                    if (e.getSource() instanceof JButton) {
                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                } 
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                else if(foreColor){
                    Component comp = (Component)e.getSource();
                    comp.setForeground(foreclr);
                    foreColor = false;
                }
                else
                    JOptionPane.showMessageDialog(Editor.this, "This is " + e.getActionCommand());
                System.out.println("Else executed");
            }
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        buttonToPlace = b;
        bckColor = false;
        foreColor = false;
    }
    
    public void addPanel(String widths,String heights) {
        panel=true;
        
        JPanel p = new JPanel();
        width = Integer.parseInt(widths);        
        height = Integer.parseInt(heights);

        p.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseClicked(MouseEvent e) {
                if (lookingToRemove) {
                        if (e.getSource() instanceof JPanel) {

                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                }  
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                
                else{
                    JOptionPane.showMessageDialog(Editor.this, "This is a panel");
                    System.out.println("Else P executed");
                }
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        panelToPlace = p;
        bckColor=false;
        foreColor=false;
    }
    
    public void addLabel(String text) {
        label=true;
        JLabel l = new JLabel(text);
        l.setOpaque(true);
        l.setBackground(Color.white);
        l.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseClicked(MouseEvent e) {
                if (lookingToRemove) {
                        if (e.getSource() instanceof JLabel) {

                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                } 
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                
                else if(foreColor){
                    Component comp = (Component)e.getSource();
                    comp.setForeground(foreclr);
                    foreColor = false;
                }
                 
                else{
                    JOptionPane.showMessageDialog(Editor.this, "This is a label");
                    System.out.println("Else label executed");
                }
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        labelToPlace = l;
        bckColor=false;
        foreColor=false;
    }
    
    public void addCheckbox(String name) {
        checkbox =true;
        JCheckBox cb = new JCheckBox(name);
        cb.setActionCommand(name);
        cb.setOpaque(true);
        cb.setBackground(Color.white);
        cb.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (lookingToRemove) {
                    if (e.getSource() instanceof JCheckBox) {
                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                } 
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                else if(foreColor){
                    Component comp = (Component)e.getSource();
                    comp.setForeground(foreclr);
                    foreColor = false;
                }
                 
                 else
                    JOptionPane.showMessageDialog(Editor.this, "This is a Checkbox" );
                System.out.println("Else executed");
            }
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        checkboxToPlace = cb;
        bckColor = false;
        foreColor = false;
    }
    
    public void addRadiobutton (String name) {
        radiobutton =true;
        JRadioButton rb = new JRadioButton(name);
        rb.setActionCommand(name);
        rb.setOpaque(true);
        rb.setBackground(Color.white);
        rb.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (lookingToRemove) {
                    if (e.getSource() instanceof JRadioButton) {
                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                } 
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                
                else if(foreColor){
                    Component comp = (Component)e.getSource();
                    comp.setForeground(foreclr);
                    foreColor = false;
                }
                 
                 else
                    JOptionPane.showMessageDialog(Editor.this, "This is RadioButton");
                System.out.println("Else executed");
            }
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        radiobuttonToPlace = rb;
        bckColor = false;
        foreColor = false;
    }
    
    public void addCombobox (String[] items) {
        combobox =true;
        JComboBox comb = new JComboBox(items);
        comb.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                if (lookingToRemove) {
                    if (e.getSource() instanceof JComboBox) {
                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                }
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                else if(foreColor){
                    System.out.println("fore");
                    Component comp = (Component)e.getSource();
                    comp.setForeground(foreclr);
                    foreColor = false;
                }
                 
                else{
                    JOptionPane.showMessageDialog(Editor.this, "This is a ComboBox");
                    System.out.println("Mouse Else executed");
                }
                    
            }
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        comboboxToPlace = comb;
        bckColor=false;
        foreColor=false;
    }
    
    public void addList (String[] items) {
        list =true;
        JList list = new JList(items);
        list.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                if (lookingToRemove) {
                    if (e.getSource() instanceof JList) {
                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                }
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                else if(foreColor){
                    System.out.println("fore");
                    Component comp = (Component)e.getSource();
                    comp.setForeground(foreclr);
                    foreColor = false;
                }
                 else
                    JOptionPane.showMessageDialog(Editor.this, "This is JList");
                System.out.println("Else executed");
            }
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        listToPlace = list;
        bckColor = false;
        foreColor = false;
    }
    
    public void addTextarea(String c, String r, String name) {
        textarea =true;
        columns = Integer.parseInt(c);        
        rows = Integer.parseInt(r);
        

        JTextArea ta = new JTextArea(name, rows, columns);
        ta.setLineWrap​(true);
        ta.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e){
                if (lookingToRemove) {
                    if (e.getSource() instanceof JTextArea) {
                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                }  
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                else if(foreColor){
                    System.out.println("fore");
                    Component comp = (Component)e.getSource();
                    comp.setForeground(foreclr);
                    foreColor = false;
                }
//                else
//                    JOptionPane.showMessageDialog(Editor.this, "This is a TextArea");
//                    System.out.println("Else executed");
            }
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        textareaToPlace = ta;
        bckColor = false;
        foreColor = false;
    }
    
    public void addTextfield(String c, String name) {
        textfield =true;
        tcolumns = Integer.parseInt(c);        

//        JTextField t = new JTextField();        
        JTextArea tar = new JTextArea(name, 20, tcolumns);

//        t.setColumns(tcolumns);
        tar.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e){                      
                System.out.println("Obejct removed3");
                if (lookingToRemove) {
                    System.out.println("Obejct removed2");
                    if (e.getSource() instanceof JTextArea) {
                        System.out.println("Obejct removed");
                        jPanel3.remove((Component) e.getSource());
                        jPanel3.validate();
                        jPanel3.repaint();
                        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                } 
                else if(bckColor){
                    Component comp = (Component)e.getSource();
                    comp.setBackground(bkclr);
                    bckColor = false;
                }
                else if(foreColor){
                    System.out.println("fore");
                    Component comp = (Component)e.getSource();
                    comp.setForeground(foreclr);
                    foreColor = false;
                }  
            }
        });
        waitingForLocationClick = true;
        lookingToRemove = false;
        textareaToPlace2 = tar;
         bckColor = false;
        foreColor = false;
    }
    
    private final MouseListener pointSelectorListener = new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (waitingForLocationClick) {
                if(button){
                    putButtonAtPoint(e.getPoint());
                }else if(panel){
                    putPanelAtPoint(e.getPoint());
                }else if(label){
                    putLabelAtPoint(e.getPoint());
                }else if(checkbox){
                    putCheckboxAtPoint(e.getPoint());
                }else if(radiobutton){
                    putRadiobuttonAtPoint(e.getPoint());
                }else if(combobox){
                    putComboboxAtPoint(e.getPoint());
                }else if(list){
                    putListAtPoint(e.getPoint());
                }else if(textarea){
                    putTextareaAtPoint(e.getPoint());
                }else if(textfield){
                    putTextfieldAtPoint(e.getPoint());
                }
            } else {
                System.out.println("Not in waiting state");
            }
        }
    };
   
    
    public void putButtonAtPoint(Point p) {
        System.out.println("Placing a button at: " + p.toString());
        jPanel3.add(buttonToPlace);
        buttonToPlace.setBounds(new Rectangle(p, buttonToPlace.getPreferredSize()));
        jPanel3.validate();
        buttonToPlace = null;
        waitingForLocationClick = false;
        button =false;
            jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }
    
    public void putPanelAtPoint(Point p) {
        System.out.println("Placing a panel at: " + p.toString());
        jPanel3.add(panelToPlace);
        panelToPlace.setLocation(p);        
        panelToPlace.setSize(width,height);
        jPanel3.validate();
        panelToPlace = null;
        waitingForLocationClick = false;
        panel =false;
        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }
    
    public void putLabelAtPoint(Point p) {
        System.out.println("Placing a label at: " + p.toString());
        jPanel3.add(labelToPlace);
        labelToPlace.setLocation(p);        
        labelToPlace.setBounds(new Rectangle(p, labelToPlace.getPreferredSize()));
        jPanel3.validate();
        labelToPlace = null;
        waitingForLocationClick = false;
        label =false;
                jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }
    
    public void putCheckboxAtPoint(Point p) {
        System.out.println("Placing a CheckBox at: " + p.toString());
        jPanel3.add(checkboxToPlace);
        checkboxToPlace.setLocation(p);        
        checkboxToPlace.setBounds(new Rectangle(p, checkboxToPlace.getPreferredSize()));
        jPanel3.validate();
        checkboxToPlace = null;
        waitingForLocationClick = false;
        checkbox =false;        
        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }

    public void putRadiobuttonAtPoint(Point p) {
        System.out.println("Placing a RadioButton at: " + p.toString());
        jPanel3.add(radiobuttonToPlace);
        radiobuttonToPlace.setLocation(p);        
        radiobuttonToPlace.setBounds(new Rectangle(p, radiobuttonToPlace.getPreferredSize()));
        jPanel3.validate();
        radiobuttonToPlace = null;
        waitingForLocationClick = false;
        radiobutton =false;
                jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }
    
    public void putComboboxAtPoint(Point p) {
        System.out.println("Placing a Combobox at: " + p.toString());
        jPanel3.add(comboboxToPlace);
        comboboxToPlace.setLocation(p);        
        comboboxToPlace.setBounds(new Rectangle(p, comboboxToPlace.getPreferredSize()));
        jPanel3.validate();
        comboboxToPlace = null;
        waitingForLocationClick = false;
        combobox =false;        
        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }
    
    public void putListAtPoint(Point p) {
        System.out.println("Placing a List at: " + p.toString());
        
        jPanel3.add(listToPlace);
        listToPlace.setBorder(BorderFactory.createLineBorder(Color.black));
        listToPlace.setLocation(p);        
        listToPlace.setBounds(new Rectangle(p, listToPlace.getPreferredSize()));
        jPanel3.validate();
        listToPlace = null;
        waitingForLocationClick = false;
        list =false;        
        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }
    
    public void putTextareaAtPoint(Point p) {
        System.out.println("Placing a textarea at: " + p.toString());
        jPanel3.add(textareaToPlace);
        textareaToPlace.setBorder(BorderFactory.createLineBorder(Color.black));
        textareaToPlace.setLocation(p);         
//        textareaToPlace.setColumns(columns);          
//        textareaToPlace.setRows(rows);        
        textareaToPlace.setSize(columns,rows);               
               
        jPanel3.validate();
        System.out.println("Success");
        textareaToPlace = null;
        waitingForLocationClick = false;
        textarea =false;
        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }
    
    public void putTextfieldAtPoint(Point p) {
        System.out.println("Placing a textfield at: " + p.toString());
//        textfieldToPlace.setBorder(BorderFactory.createLineBorder(Color.black));
        jPanel3.add(textareaToPlace2);        
        textareaToPlace2.setBorder(BorderFactory.createLineBorder(Color.black));        
        textareaToPlace2.setLocation(p);
            textareaToPlace2.setSize(tcolumns,20); 
               
        jPanel3.validate();
        System.out.println("Success");
        textfieldToPlace = null;
        waitingForLocationClick = false;
        textfield =false;
        jPanel3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
            
        });
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BckColor;
    private javax.swing.JButton ForeColor;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addCheckbox;
    private javax.swing.JButton addCombobox;
    private javax.swing.JButton addLabel;
    private javax.swing.JButton addList;
    private javax.swing.JButton addPanel;
    private javax.swing.JButton addRadiobutton;
    private javax.swing.JButton addTextarea;
    private javax.swing.JButton addTextfield;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
